// Generated by CoffeeScript 1.12.4
var ReactiveVar, inject;

ReactiveVar = require("./ReactiveVar");

inject = require("Property/inject");

inject("ReactiveVar", ReactiveVar);

module.exports = ReactiveVar;
