// Generated by CoffeeScript 1.12.4
var Any, Tracker, Type, type;

Tracker = require("tracker");

Type = require("Type");

Any = require("Any");

type = Type("ReactiveVar");

type.defineArgs(function() {
  return {
    required: false,
    types: [Any, String]
  };
});

type.defineValues(function(value, keyPath) {
  return {
    _dep: Tracker.Dependency(),
    _value: value,
    _keyPath: keyPath
  };
});

type.defineGetters({
  keyPath: function() {
    return this._keyPath;
  }
});

type.defineMethods({
  compare: function(oldValue, newValue) {
    return oldValue === newValue;
  },
  get: function() {
    if (Tracker.isActive) {
      this._dep.depend();
    }
    return this._value;
  },
  set: function(newValue) {
    if (this.compare(this._value, newValue)) {
      return;
    }
    this._value = newValue;
    this._dep.changed();
  },
  add: function(value) {
    return this.set(this._value + value);
  },
  sub: function(value) {
    return this.set(this._value - value);
  },
  _numListeners: function() {
    var count, i, id, len, ref;
    count = 0;
    ref = Object.keys(this._dep._dependentsById);
    for (i = 0, len = ref.length; i < len; i++) {
      id = ref[i];
      count += 1;
    }
    return count;
  }
});

module.exports = type.build();
